### ISSUE TITLE
Start transaction from Kotlin coroutine

### ISSUE THREAD

**Issue by yonigibbs** [reactiverse/reactive-pg-client#154]
Hi,

I'm wrapping the callback-based approach which reactive-pg-client uses, with Kotlin coroutines, as explained in the coroutine documentation [here](https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md#wrapping-callbacks) (fourth code block).  This is all working great.  However, when I try to begin a transaction I get an error.

Here's the callback-style code, which all works fine:
```
    connectionPool.getConnection { res ->
        if (res.succeeded()) {
            val connection = res.result()
            val transaction = connection.begin()   // This succeeds
```

Here's the coroutine code, which fails:
```
    val connection = awaitResult<PgConnection> { connectionPool.getConnection(it) }
    try {
        val transaction = connection.begin()    // This fails
```
The latter approach calls `awaitResult`, which is more or less a copy of what's in the coroutine documentation linked above:
```
suspend inline fun <T> awaitResult(crossinline block: (Handler<AsyncResult<T>>) -> Unit): T {
    return suspendCoroutine { cont ->
        try {
            block(Handler { asyncResult ->
                if (asyncResult.succeeded()) cont.resume(asyncResult.result())
                else cont.resumeWithException(asyncResult.cause())
            })
        } catch (e: Exception) {
            cont.resumeWithException(e)
        }
    }
}
```
The error stack trace is shown below. The problem seems to be that in `io.reactiverse.pgclient.impl.SockeConnection.schedule()` there is this code:
```
    if (Vertx.currentContext() != context) {
      throw new IllegalStateException();
    }
```
When I step through the code, `Vertx.currentContext()` returns null, hence the exception.

Any idea if I'm doing something wrong here, or if it's a bug?  In case it makes a difference, I'm running this in a standard `main` method, just as a test, and I'm moving from normal code into a suspending/coroutine "context" (not sure if that's the right word) by calling `runBlocking` at the start of my `main` method.

Thanks.

**Full error stack trace:**
```
java.lang.IllegalStateException
	at io.reactiverse.pgclient.impl.SocketConnection.schedule(SocketConnection.java:168)
	at io.reactiverse.pgclient.impl.ConnectionPool$PooledConnection.schedule(ConnectionPool.java:81)
	at io.reactiverse.pgclient.impl.Transaction.<init>(Transaction.java:45)
	at io.reactiverse.pgclient.impl.PgConnectionImpl.begin(PgConnectionImpl.java:113)
	at io.reactiverse.pgclient.impl.PgConnectionImpl.begin(PgConnectionImpl.java:106)
	at com.yg.pgvoltest1.VertxUtilsKt.executeBatch(VertxUtils.kt:46)
	at com.yg.pgvoltest1.VertxUtilsKt$executeBatch$1.doResume(VertxUtils.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:14)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:136)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:133)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:52)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:41)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Unknown Source)
	at [my main method]
```

**Comment by vietj** [comment]
can you provide a reproducer so I can investigate ?

**Comment by yonigibbs** [comment]
Sure. The sample code below is enough to get it to fail on my system. I just run it as a standard Java application from within IntelliJ.  Let me know if there's anything else you need.

```
package test.test

import io.reactiverse.pgclient.PgClient
import io.reactiverse.pgclient.PgConnection
import io.reactiverse.pgclient.PgPoolOptions
import io.vertx.core.AsyncResult
import io.vertx.core.Handler
import kotlinx.coroutines.experimental.runBlocking
import kotlin.coroutines.experimental.suspendCoroutine

fun main(args: Array<String>) {
    val connectionPool = PgClient.pool(PgPoolOptions.fromUri("postgresql://test:5432/test")
            .setUser("test")
            .setPassword("test")
            .setMaxSize(10))

    runBlocking {
        val connection = awaitResult<PgConnection> { connectionPool.getConnection(it) }
        try {
            val transaction = connection.begin()    // This line errors
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            connection.close()
        }
    }
}

private suspend inline fun <T> awaitResult(crossinline block: (Handler<AsyncResult<T>>) -> Unit): T {
    return suspendCoroutine { cont ->
        try {
            block(Handler { asyncResult ->
                if (asyncResult.succeeded()) cont.resume(asyncResult.result())
                else cont.resumeWithException(asyncResult.cause())
            })
        } catch (e: Exception) {
            cont.resumeWithException(e)
        }
    }
}
```

**Comment by vietj** [comment]
can you provide a small github project i t's easier thanks

**Comment by yonigibbs** [comment]
No problem. Do you want anything related to a Postgres DB in there, e.g. a Docker file and SQL to create a sample DB, etc?  Or are you happy to just take the project and point it at some Postgres DB you've got up and running already?

**Comment by vietj** [comment]
a docker image would be great, look at the Docker folder in this project it has an example of docker image setup

**Comment by yonigibbs** [comment]
No problem at all.  Repo available here: https://github.com/yonigibbs/rpgc-coroutine-tx

**Comment by vietj** [comment]
thanks I will investigate

**Comment by vietj** [comment]
can you provide a project that creates a fatjar to run ? it's easier, my current IDE can't run your project

**Comment by yonigibbs** [comment]
Yup, no problem at all.  Haven't worked with fat jars before so not 100% sure I've done it right, but grab the latest from that repo of mine and hopefully it should be OK.  Any problems let me know and I'll spend more time looking at it in more detail.

**Comment by vietj** [comment]
sure, I'm using intellij CE 2018.1 and it could not run the project as is

**Comment by mkulak** [comment]
I can confirm that current transactions doesn't get well with coroutines.
I have workaround for it. which is not using transaction API but rather start transaction manually:
```kotlin
    override suspend fun <T> tx(block: suspend (PgConnection) -> T): T {
        val con = getConnection(pool)
        return try {
            awaitResult<PgRowSet> { con.query("BEGIN", it) }
            val res = block(con)
            awaitResult<PgRowSet> { con.query("COMMIT", it) }
            res
        } catch (e: Exception) {
            rollback(con)
            throw e
        } finally {
            con.close()
        }
    }
    private suspend fun rollback(con: PgConnection) {
        try {
            awaitResult<PgRowSet> { con.query("ROLLBACK", it) }
        } catch (e: Exception) {
            logger.error(null, "Exception while ROLLBACK", e)
        }
    }

    private suspend fun getConnection(pool: PgPool) =
        measure.connection {
            awaitResult<PgConnection> { pool.getConnection(it) }
        }.exceptionHandler { ex ->
            logger.error(null, "PgConnection exceptionHandler:", ex)
        }

```

But it would be nice to have built-in coroutine-friendly API for transactions.

**Comment by vietj** [comment]
have you tried this with the latest version of the project 0.10.6 ?

**Comment by vietj** [comment]
will investigate the reproducer provided by @yonigibbs

**Comment by vietj** [comment]
this actually works with 0.10.6, I believe this issue was fixed by https://github.com/reactiverse/reactive-pg-client/issues/162

**Comment by vietj** [comment]
@mkulak what you are observing might be a different issue, can you open a new issue with a reproducer project ?

**Comment by vietj** [comment]
fixed by https://github.com/reactiverse/reactive-pg-client/issues/162

**Comment by yonigibbs** [comment]
I can confirm that upgrading to 10.6 seems to resolve this problem.  Thanks @vietj.
