### ISSUE TITLE
Can not rollback transaction

### ISSUE THREAD

**Issue by happyyangyuan** [reactiverse/reactive-pg-client#156]
**reactive-pg-client version: 0.10.1**    
I get the exception below when I try to rollback a begun transaction with 1 statement executed.
`java.lang.RuntimeException: rollback exception
        at io.reactiverse.pgclient.impl.Transaction.lambda$wrap$1(Transaction.java:113)
        at io.reactiverse.pgclient.impl.SocketConnection.handleMessage(SocketConnection.java:222)
        at io.reactiverse.pgclient.impl.SocketConnection.lambda$initiateProtocol$1(SocketConnection.java:110)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
        at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:242)
        at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:239)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.reactiverse.pgclient.impl.CommandBase.handleReadyForQuery(CommandBase.java:126)
        at io.reactiverse.pgclient.impl.PrepareStatementCommand.handleReadyForQuery(PrepareStatementCommand.java:80)
        at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeReadyForQuery(MessageDecoder.java:247)
        at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:106)
        at 
...
`

**Comment by vietj** [comment]
it means that the statement you executed failed and the transaction rolled back.

can you check the statement you executed result ?

**Comment by happyyangyuan** [comment]
Well, I debug my code again and find that before the first sql execution result notification submit the second sql will cause the reactive-pg-client call rollback method. At this time a rollback will certainly fail.
Thanks.
