### ISSUE TITLE
Can not insert data with tx.preparedQuery

### ISSUE THREAD

**Issue by foxgem** [reactiverse/reactive-pg-client#237]
PgTransaction.preparedQuery could not work. Here is an example with PG 9.4:

~~~
pgPool.begin(res -> {
    if (res.succeeded()) {
        PgTransaction tx = res.result();

        // table: create table test (id bigserial not null, topic varchar(10) not null);
        tx.query("insert into test (topic) values ('topic')", this::voidHandler);
        tx.preparedQuery("insert into test (topic) values ($1)", Tuple.of("topic"), this::voidHandler);

        tx.commit(ar -> {
            if (ar.succeeded()) {
                // ...
            } else {
                // ...
            }
        });
    }
})

// log error only
private void voidHandler(AsyncResult<PgRowSet> result) {
    if (result.failed()) {
        logger.error("Sql execution failed, cause: {}", result.cause());
    }
}
~~~

In the example above, the first insert stmt with "tx.query" can insert data successfully. However, for the second insert stmt with "tx.preparedQuery", you can get an exception as below:

~~~
2019-01-15 11:53:52,850 [vert.x-eventloop-thread-0] ERROR t.d.e.clock.job.AbstractJobHandler - Sql execution failed, cause: {}
io.vertx.core.VertxException: Transaction already completed
	at io.reactiverse.pgclient.impl.Transaction.checkPending(Transaction.java:90)
	at io.reactiverse.pgclient.impl.Transaction.lambda$wrap$3(Transaction.java:138)
	at io.reactiverse.pgclient.impl.Transaction$$Lambda$102/316707258.handle(Unknown Source)
	at io.reactiverse.pgclient.impl.SocketConnection$CachedPreparedStatement.handle(SocketConnection.java:138)
	at io.reactiverse.pgclient.impl.SocketConnection$CachedPreparedStatement.handle(SocketConnection.java:120)
	at io.reactiverse.pgclient.impl.SocketConnection.handleMessage(SocketConnection.java:227)
	at io.reactiverse.pgclient.impl.SocketConnection.lambda$initiateProtocol$1(SocketConnection.java:110)
	at io.reactiverse.pgclient.impl.SocketConnection$$Lambda$43/1734258255.handle(Unknown Source)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:386)
	at io.vertx.core.net.impl.VertxHandler$$Lambda$34/865980259.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder$$Lambda$39/308953605.handle(Unknown Source)
	at io.reactiverse.pgclient.impl.CommandBase.handleReadyForQuery(CommandBase.java:126)
	at io.reactiverse.pgclient.impl.PrepareStatementCommand.handleReadyForQuery(PrepareStatementCommand.java:79)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeReadyForQuery(MessageDecoder.java:247)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
~~~

I also tried another way with the following steps:

~~~
1. get connection from pool
1. begin tx with connection
1. connection.preparedQuery
1. tx.commit
~~~

But, no luck.

The code above is running with 0.11.1 version.

**Comment by vietj** [comment]
can you provide a reproducer test in this project test suite as PR to facilitate ?

**Comment by foxgem** [comment]
Sorry for late response since too busy these days. I just post a PR for this issue including two test cases. Please check it, thanks.

**Comment by quandragoon** [comment]
@vietj @foxgem I run into this problem too on 0.11.3
Has there been a fix? Else, how should I run preparedQuery in a transaction?

**Comment by vietj** [comment]
I think now the test pass, can you provide a new test with your case ?

**Comment by vietj** [comment]
and open a new issue
