### ISSUE TITLE
rxPreparedQuery delete

### ISSUE THREAD

**Issue by perttuk** [reactiverse/reactive-pg-client#265]
Hi,

I'm using rxPreparedQuery method to delete old rows from table.

```
DELETE FROM
    table
WHERE
    date_created < (NOW() AT TIME ZONE 'utc') - INTERVAL '$1 DAYS'
```
``
pgPool.rxPreparedQuery(SQL_DELETE, Tuple.of(31))
``

and the error is

``
io.vertx.core.impl.NoStackTraceThrowable: Values [31] cannot be coerced to []
``

If I hardcode the days and use ``rxPreparedQuery("DELETE FROM..")`` everything works fine. Is there something wrong with the syntax I'm using? Library version is 0.11.3

**Comment by BillyYccc** [comment]
I think you should treat the whole `INTERVAL '$1 DAYS'` as a parameter of `INTERVAL` type to send, so you can write SQL like 
```
DELETE FROM
    table
WHERE
    date_created < (NOW() AT TIME ZONE 'utc') - $1
```
and pass the parameter with 
`pgPool.rxPreparedQuery(SQL_DELETE, Tuple.of(Interval.of(0, 0, ${your_days_to_pass})))`

can you give this a try?

**Comment by perttuk** [comment]
Thanks for response! With
``pgPool.rxPreparedQuery(SQL_DELETE, Tuple.of(Interval.of(0, 0, daysToKeep)))`` 
The following exception is thrown
``io.vertx.core.impl.NoStackTraceThrowable: Values [Interval( 0 years 0 months 31 days 0 hours 0 minutes 0 seconds )] cannot be coerced to []``

**Comment by perttuk** [comment]
Thanks for the response! You got me on right tracks :)

``pgPool.rxPreparedQuery(SQL_DELETE_LISTINGS, Tuple.of(Interval.of(0, 0, daysToKeep)))``
```
DELETE FROM
    table
WHERE
    date_created < (NOW() AT TIME ZONE 'utc') - $1
```
Results in
```
io.reactiverse.pgclient.PgException: operator does not exist: timestamp with time zone < interval
	at io.reactiverse.pgclient.impl.PrepareStatementCommand.handleErrorResponse(PrepareStatementCommand.java:73)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeError(MessageDecoder.java:253)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeMessage(MessageDecoder.java:142)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
But everything works after changing SQL to
```
DELETE FROM
    table
WHERE
    date_created < (NOW() AT TIME ZONE 'utc') - $1::INTERVAL
```
Thanks!
